// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAXZBGcaU-gjyzqY_p3jk4CRkcVchYKQw',
    appId: '1:285092418551:web:f91c8b44580b3fd56694f2',
    messagingSenderId: '285092418551',
    projectId: 'firstfirebase-61c36',
    authDomain: 'firstfirebase-61c36.firebaseapp.com',
    storageBucket: 'firstfirebase-61c36.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGcJshFG4n0vc0CggCvEDtd2WaMHhO94g',
    appId: '1:285092418551:android:745eb0ff8c40b2eb6694f2',
    messagingSenderId: '285092418551',
    projectId: 'firstfirebase-61c36',
    storageBucket: 'firstfirebase-61c36.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIscBSCWXUIzsf-UkedmUGFDPr0xIfBg8',
    appId: '1:285092418551:ios:dfa692aa1e576fa26694f2',
    messagingSenderId: '285092418551',
    projectId: 'firstfirebase-61c36',
    storageBucket: 'firstfirebase-61c36.appspot.com',
    iosClientId: '285092418551-neo5s1fmuk2vh9a75rs54ukfuiksrlph.apps.googleusercontent.com',
    iosBundleId: 'com.example.medchain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIscBSCWXUIzsf-UkedmUGFDPr0xIfBg8',
    appId: '1:285092418551:ios:dfa692aa1e576fa26694f2',
    messagingSenderId: '285092418551',
    projectId: 'firstfirebase-61c36',
    storageBucket: 'firstfirebase-61c36.appspot.com',
    iosClientId: '285092418551-neo5s1fmuk2vh9a75rs54ukfuiksrlph.apps.googleusercontent.com',
    iosBundleId: 'com.example.medchain',
  );
}
